const SET_TEMP_NAME = 'SET_NAME';
const SET_TEMP_MIN_CONFIRMED = 'SET_MIN_CONFIRMED';
const SET_TEMP_MAX_CONFIRMED = 'SET_MAX_CONFIRMED';
const SET_FILTER = 'SET_FILTER';
const CANCEL_FILTER = 'CANCEL_FILTER';
const RESET_FILTER = 'RESET_FILTER';

export { SET_TEMP_NAME, SET_TEMP_MIN_CONFIRMED, SET_TEMP_MAX_CONFIRMED, SET_FILTER, CANCEL_FILTER, RESET_FILTER };