const SET_LOCATIONS = 'SET_LOCATIONS';
const SET_LOCATIONS_LOADING = 'SET_LOCATIONS_LOADING';
const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
const SET_SELECTED_LOCATION_LOADING = 'SET_SELECTED_LOCATION_LOADING';

export { SET_LOCATIONS, SET_LOCATIONS_LOADING, SET_SELECTED_LOCATION, SET_SELECTED_LOCATION_LOADING };
