const SET_LOCATION_ARRAY = 'SET_LOCATION_ARRAY';
const SET_LOCATION_ARRAY_LOADING = 'SET_LOCATION_ARRAY_LOADING';
const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
const SET_SELECTED_LOCATION_LOADING = 'SET_SELECTED_LOCATION_LOADING';

export { SET_LOCATION_ARRAY, SET_LOCATION_ARRAY_LOADING, SET_SELECTED_LOCATION, SET_SELECTED_LOCATION_LOADING };